/* ATTENTION: Do not edit this file for no good reason!!!. This is a kernel file, and the performance of the entire system depends on its contents. */

window.vxg = window.vxg || {};
vxg.api = vxg.api || {};
vxg.api.necam = vxg.api.necam || {};
vxg.api.necam.apiSrc = vxg.api.necam.apiSrc || window.location.origin;
vxg.api.necam.user = vxg.api.necam.user || {};

//////////////////////////////////////////////////
// User api

vxg.api.necam.user.login = function(obj){
    var d = $.Deferred();
    if (obj['password']) {
alert('only firebase support!');
//	obj.password = CryptoJS.SHA3(obj.password, {outputLength: vs_api.hashBits}).toString(CryptoJS.enc.Base64);
    } 
/*
    else if (vs_api['token'] && vs_api.token !== '') {
        if (!obj['token'])
            obj['token'] = vs_api.token;
//        obj['uid'] = vs_api.uid;
        if (vs_api.manage_uid)
            obj['manage_uid'] = vs_api.manage_uid;
    }
*/
	if ($.isEmptyObject(obj)) {
		setTimeout(d.reject,10);
    } else {
        $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc + '/api/v1/user/login/',
            contentType: "application/json",
            data: JSON.stringify(obj)
        }).done(function(r){
// TODO: old authorisation - delete if no need
/*
            vs_api.token = r.token;
            vs_api.uid = r.uid;
            if (r['dealerUID'])
                vs_api.dealerUID = r.dealerUID;
            vs_api.role = r.role;
            if (obj['password']) {
                localStorage.removeItem("manage_uid");
                localStorage.removeItem("manage_uid_path");
            }
            if(obj["remember_me"] && obj["remember_me"] === true){
                localStorage.setItem("api_token", vs_api.token);
            }else{
                sessionStorage.setItem("api_token", vs_api.token);
            }
            if (r['settings']) {
                vs_api.options = r['settings'];
            }
            localStorage.setItem("uid", vs_api.uid);
*/
//            createManagePath();
            d.resolve(r);
        }).fail(function(r){
            localStorage.removeItem("api_token");
            sessionStorage.removeItem("api_token");
            d.reject(r);
        });
    }
	return d.promise();
};

vxg.api.necam.user.list = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/list/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.user.update = function(obj){
//    if (obj['password']) obj.password = CryptoJS.SHA3(obj.password, {outputLength: vs_api.hashBits}).toString(CryptoJS.enc.Base64);
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/update/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.user.del = function(partnerID){
    var data = {id: partnerID};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/del/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.user.relation = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/relation/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.user.invite = function(obj){
//    if (obj['password']) obj.password = CryptoJS.SHA3(obj.password, {outputLength: vs_api.hashBits}).toString(CryptoJS.enc.Base64);
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/invite/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.user.change_password = function(obj){
alert('Function non supported');
};

vxg.api.necam.user.getUsedPlans = function(){
    var data = {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/getusedplans/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};



//////////////////////////////////////////////////
// Camera api

vxg.api.necam.camera = vxg.api.necam.camera || {}

vxg.api.necam.camera.setPlans = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/plan/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.camera.list = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/list/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.camera.getLocations = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/getlocations/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.camera.setLocations = function(channel_id, location){
    var data = {channel_id:channel_id, location:location};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/setlocation/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.camera.update = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/update/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.camera.del = function(cameraID){
    var data = {id: cameraID};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/del/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

//////////////////////////////////////////////////
// Map api

vxg.api.necam.addresses = vxg.api.necam.addresses || {};

vxg.api.necam.addresses.list = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/addresses/list/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.addresses.upload = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/addresses/upload/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.addresses.del = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/addresses/del/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.addresses.find = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/addresses/find/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};

vxg.api.necam.camera.add = function(obj){
    var data = obj || {};
//    data.uid = vs_api.uid;
//    if (vs_api.manage_uid)
//        data.manage_uid = vs_api.manage_uid;
    return vxg.user.getToken().then(function(r){
        data.token = r;
        return $.ajax({
            type: 'POST',
            url: vxg.api.necam.apiSrc+'/api/v1/user/camera/add/',
            contentType: "application/json",
            data: JSON.stringify(data)
        });
    });
};
